samples:
  - SRR000648

reference:
  name: Saccharomyces_cerevisiae.R64-1-1.dna.toplevel
  url: "https://ftp.ensembl.org/pub/release-111/fasta/saccharomyces_cerevisiae/dna/Saccharomyces_cerevisiae.R64-1-1.dna.toplevel.fa.gz"
