name: rnaseq-pipeline
channels:
  - bioconda       # put bioconda first
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - snakemake
  - fastqc
  - cutadapt
  - star
  - salmon
  - samtools
  - r-base
  - bioconductor-deseq2
  - bioconductor-tximport
  - r-ggplot2
  - r-pheatmap
  - r-tidyverse
  - fastq-dl
  - multiqc

